site_name: AutoPI
site_description: Documentation sur le projet AutoPI
site_author: Gabriel Bolduc

theme:
  name: material
  icon:
    logo: material/car-connected
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search

nav:
  - Introduction: index.md
  - Architecture Matérielle & Backend: 
    - Hardware: AMB/hardware.md
    - Spécifications OpenSpec: AMB/specs.md
    - Données de Télémétrie: AMB/telemetrie.md
    - Logique Backend: AMB/backend.md