site_name: AutoPI
site_description: Documentation sur le projet AutoPI
site_author: Gabriel Bolduc

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search

nav:
  - Introduction: Proposition_Formelle/Proposition_formelle.md
  - Architecture Matérielle: 
    - Configuration du Pi: hardware/pi_setup.md
    - Adaptateur OBD2: hardware/obd2_veepeak.md
  - Backend & Spécifications:
    - Contrat OpenSpec: backend/specs.md